In [3]:
import numpy as np

In [4]:
A = np.array([[56.0,  0.0,  4.4,  68.0],
              [ 1.2, 104.0, 52.0,   8.0],
              [ 1.8, 135.0, 99.0,   0.9]])

In [5]:
sum=A.sum(axis=0)

In [6]:
sum

array([ 59. , 239. , 155.4,  76.9])

In [7]:
sum.shape

(4,)

In [8]:
sum.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [9]:
A/sum

array([[0.94915254, 0.        , 0.02831403, 0.88426528],
       [0.02033898, 0.43514644, 0.33462033, 0.10403121],
       [0.03050847, 0.56485356, 0.63706564, 0.01170351]])

In [10]:
A/sum*100

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [13]:
B = np.array([
    [4],
    [2],
    [6],
    [1]
])

In [14]:
B.shape

(4, 1)

In [17]:
B

array([[4],
       [2],
       [6],
       [1]])

In [15]:
B*100

array([[400],
       [200],
       [600],
       [100]])

<img src="./images/100.png" alt="Alt text" width="300"/>

In [19]:
C = np.array([[1, 2, 3],
              [4, 5, 6]])

In [20]:
C.shape

(2, 3)

In [23]:
D= np.array([[100, 200, 300]])

In [24]:
D.shape

(1, 3)

In [25]:
C+D

array([[101, 202, 303],
       [104, 205, 306]])

<img src="./images/2.png" alt="Alt text" width="600"/>