In [1]:
import numpy as np

In [2]:
A=np.random.rand(5)

In [3]:
A

array([0.74109796, 0.61865968, 0.25123709, 0.81303848, 0.41198591])

### This is not a Column or Row vector

In [4]:
A.shape

(5,)

In [5]:
A.T

array([0.74109796, 0.61865968, 0.25123709, 0.81303848, 0.41198591])

# ??

<img src="./images/3.png">

In [12]:
A=np.random.randn(5,1)

In [13]:
A

array([[ 0.63625412],
       [-1.08026108],
       [ 0.96167808],
       [ 0.07937217],
       [ 0.36527513]])

In [14]:
A.T

array([[ 0.63625412, -1.08026108,  0.96167808,  0.07937217,  0.36527513]])

In [16]:
A.shape

(5, 1)

In [17]:
A.T.shape

(1, 5)

In [21]:
B=np.random.rand(5)

In [22]:
B

array([0.81856152, 0.15354896, 0.39071844, 0.41909211, 0.8518298 ])

In [23]:
B.reshape(1,5)

array([[0.81856152, 0.15354896, 0.39071844, 0.41909211, 0.8518298 ]])

In [24]:
B.reshape(5,1)

array([[0.81856152],
       [0.15354896],
       [0.39071844],
       [0.41909211],
       [0.8518298 ]])

In [25]:
a=np.array([[3,4],[1,2]])

In [26]:
a

array([[3, 4],
       [1, 2]])

In [27]:
np.dot(a,a)

array([[13, 20],
       [ 5,  8]])